[package]
name = "patient_id_resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
tokio = { version = "1.28.2", features = ["full"] }
reqwest = { version = "0.11.18", features = ["json"] }
serde_json = "1.0.96"
config = "0.13.3"